Logos and icons.
scipp/essnmx pull request #19
Opened 2024-01-09 14:59 UTC by YooSunYoung

Static logo and icon images for documentation pages.

- [x] favicon.cio
- [x] logo.svg (text converted to path)
- [x] logo-dark.svg (text converted to path)
- [x] logo-text.svg (text as text with font indicated)

2024-01-09 15:26 UTC, SimonHeybrock requested changes

2024-01-09 15:26 UTC, SimonHeybrock commented on docs/_static/logo-text.svg
Looks like wrong font on this one?

2024-01-09 15:26 UTC, SimonHeybrock commented on docs/_static/logo.svg
Generally we keep the non-path version for enabling future modifications, typically in `resources/`. Why did you add it here? I think the docs use only two files, right?

2024-01-10 08:16 UTC, YooSunYoung commented on docs/_static/logo.svg
Yes, sorry...! I will relocate this file.

2024-01-10 08:16 UTC, YooSunYoung commented on docs/_static/logo-text.svg
I just copied scipp logo and made them into path though...?

2024-01-10 10:22 UTC, SimonHeybrock approved these changes

2024-01-10 10:47 UTC, merged