fix: load single bank
scipp/essnmx pull request #51
Opened 2024-03-15 12:10 UTC by jokasimr

Fixes #49

2024-03-18 04:52 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    return events.group(pixel_ids).fold(dim='id', sizes={'panel': 1, 'id': -1})
Shouldn't the `panel` dimension be gone now? Why do we still have to fold?

2024-03-18 04:52 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
>  import scippnexus as snx
A couple lines below: Not your change, but why do we have `DetectorName` and `DetectorBankName`? Can we remove the latter?

2024-03-18 04:52 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    )
It seems like the `read_mcstas_geometry_xml` is loading all banks? Is this something that should also be split up, alongside these changes, instead of disentangling it here? Hard-coding the detector names here looks very odd anyway.

2024-03-18 08:17 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +    return events.group(pixel_ids).fold(dim='id', sizes={'panel': 1, 'id': -1})
For now just because some of the tests expects it to be there. I'll remove it and change the tests.

2024-03-18 08:19 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +    )
Yeah should have put a comment that this is a placeholder solution. I don't really know how to to this disentangling in a sensible way. It's possible to do it based on the McStas run definition code, but that seems a bit cumbersome.

2024-03-18 09:02 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +    )
I'm not sure what you mean. The old code loaded all detectors and here we only want to load one.

2024-03-18 09:11 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    )
The old code did not have to spell out the mapping here. Why do we have to now?

2024-03-18 09:47 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +    )
Because we only want to load one bank, and also only the detector that is associated with the bank we're loading. The old code loaded all banks and also loaded all detectors.

2024-03-18 10:01 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    )
My points is: The previous implementation simply used a positional (sorted) association. There was no need to hard-code a mapping here, relying on any particular naming scheme. Why can't we keep doing the same, e.g., by using a bank index?

2024-03-18 11:34 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +    )
Yeah maybe we can do that. I mean, that depends on if we can rely on the ordering of the banks being the same as the ordering of the detectors. The order of the banks is the order they occur in the nexus file I guess, and the entries in a HDF group are ordered alphanumerically.

The old code doesn't really need the banks and the detectors having the same order (I think) it only assumes the detectors are ordered by their respective `detector_ids`.

2024-03-19 14:22 UTC, YooSunYoung reviewed
I think it'll be easier to use integer index of detector instead of hard-coded detector name.
We just need to make sure that they are sorted in the order of pixel-ids.

And if there is no events to compare the pixel ids in the banks,
it doesn't matter really which detector bank to use, so it can be just sorted by their names
Even though there is no events, it should still be possible to load the geometry, for example ``pixel-ids`` and ``pixel-offsets``.

2024-03-19 14:22 UTC, YooSunYoung commented on src/ess/nmx/mcstas_loader.py
> +            ('nD_Mantid_0', 'nD_Mantid_1', 'nD_Mantid_2'),
I think we don't really need this dictionary if we use an integer index of detector/bank, and make sure we sorted them in the order of pixel ids they carry as Simon mentioned.

2024-03-19 14:45 UTC, jokasimr commented
Noticed just now that one of the two test files (mcstas2) puts all events from the three detectors into the same event data list.
It makes things complicated because in that case things needs to work differently from the case when each event data bank is associated with a separate detector.

I'm wondering if this is something we should support right now, I think it would be easier to develop this from the assumption that each `event_data_bank` is associated with only one detector panel.

2024-03-19 14:51 UTC, YooSunYoung commented
> Noticed just now that one of the two test files (mcstas2) puts all events from the three detectors into the same event data list.

Yeah... that was why it was loading in all possible banks from the first place.
I think we can just use the only bank if it fails to find the related one.
It'll drop all unused pixels anyways.

> I'm wondering if this is something we should support right now, I think it would be easier to develop this from the assumption that each event_data_bank is associated with only one detector panel.

I'm not sure ... especially since Aaron is in process of handling over Justin's work these days.
@Justin-Bergmann , @aaronfinke do you still need McStas 2 results?

2024-03-19 15:15 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +            ('nD_Mantid_0', 'nD_Mantid_1', 'nD_Mantid_2'),
Replaced the hardcoded association with a regex that looks in the mcstas definition file for detectors and the event datasets they are associated with.

2024-03-22 13:09 UTC, YooSunYoung commented on docs/examples/workflow.ipynb
> +    "    DetectorBankName,\n",
Now that we can map the `detector name` to `detector bank name`,
should we maybe use `detector name` instead of the bank name as a user input...?
Which one comes first...? `DetectorName` or `DetectorBankName`...?

2024-03-22 13:09 UTC, YooSunYoung commented on src/ess/nmx/mcstas_loader.py
> +def _retrieve_raw_event_data(file: snx.File, bank_name: str) -> sc.Variable:
I thought we could find the full name of the detector data bank in the mcstas description.
Is it just prefix that we can find...?

2024-04-08 08:47 UTC, YooSunYoung requested changes

2024-04-08 08:47 UTC, YooSunYoung commented on docs/examples/workflow.ipynb
> +  },
Can you remove this code cell? It might make documentation build quite slow.

2024-04-08 08:47 UTC, YooSunYoung commented on src/ess/nmx/const.py
> +DETECTOR_DIM = 'panel'
This line seems same as line #1.

2024-04-08 08:47 UTC, YooSunYoung commented on src/ess/nmx/mcstas_loader.py
> +    return f'nD_Mantid_{index}'
Is this function not used?

2024-04-08 08:47 UTC, YooSunYoung commented on src/ess/nmx/mcstas_xml.py
> +            'origin_position': sc.concat(origins, DETECTOR_DIM),
Will they still have a `DETECTOR_DIM` even if it is only from 1 detector...?
If yes, should `pixel_id` and `position` also have `DETECTOR_DIM`...?

2024-04-08 08:47 UTC, YooSunYoung commented on src/ess/nmx/types.py
> +DetectorGeometry = NewType("DetectorGeometry", Any)
Will you also update the api-reference page to have ``nmx.types``...?

2024-04-08 08:51 UTC, jokasimr commented on src/ess/nmx/const.py
> +DETECTOR_DIM = 'panel'
I don't understand what you mean ;) does this code already exist elsewhere?

2024-04-08 08:52 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +    return f'nD_Mantid_{index}'
Yes it's used, it's exported as a provider.

2024-04-08 08:54 UTC, jokasimr commented on src/ess/nmx/mcstas_xml.py
> +            'origin_position': sc.concat(origins, DETECTOR_DIM),
Yes they will still have the detector dimension even if it is only one detector.
I'm not sure if they should or not. But I figured that it doesn't really matter if they do, so I left it.

2024-04-08 08:55 UTC, jokasimr commented on docs/examples/workflow.ipynb
> +  },
Yes sure, good point.

2024-04-08 12:02 UTC, YooSunYoung commented on src/ess/nmx/const.py
> +DETECTOR_DIM = 'panel'
Ah sorry I meant line#5 and line#1 are repeated.

2024-04-08 12:37 UTC, jokasimr commented on src/ess/nmx/mcstas_loader.py
> +def _retrieve_raw_event_data(file: snx.File, bank_name: str) -> sc.Variable:
We can only get the prefix, the full name is something that contains all the variables in the data: `bank01_events_dat_list_p_x_y_n_id_t` but the name we extract form the mcstas description is just `bank_01_events.dat`

2024-04-10 14:08 UTC, YooSunYoung approved these changes

2024-04-10 14:20 UTC, merged