McStas data loader and minimal data reduction as an example.
scipp/essnmx pull request #9
Opened 2023-12-12 13:34 UTC by YooSunYoung

Related to #6.

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
Should we rename this file to `mcstas_loader.py` or something like that?

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +InputFileName = NewType("InputFileName", str)
```suggestion
InputFilename = NewType("InputFilename", str)
```

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +    var = original_var.copy().astype(dtype) if dtype else original_var.copy()
```suggestion
    original_var = var[dim, idx].copy()
    var = original_var.astype(dtype) if dtype else original_var
```
?

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +            raise NotImplementedError("Measurement data loader is not implemented yet.")
This is not going to work. "ESS" NeXus files may also have an entry named "entry1" (naming is arbitrary). I think we should not attempt to auto-detect the file. Simply remove everything that is not for McStas. Name the function `load_mcstas` or something like that?

Not sure it matters here, but you could also look for a unique top-level entry (this is the most common case), instead of a fixed name.

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +    t_list = copier(idx=5, unit='s')
I don't feel the code got more readable by having `partial` here. Can you just call the function directly? The `dim_1` might just as well be hard-coded, it doesn't seem like there are any other cases?

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +    id_list = copier(idx=4, unit='dimensionless', dtype="int64")
IDs should never have a unit, use `unit=None`, otherwise a bunch of operations may not work as expected.

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +    return NMXData(Events(loaded), pixel_ids)
Why the helper class? Shouldn't we group directly here?

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +        if key.startswith("bank01_events_dat_list"):
Should we include the list of required fields (which I think was also encoded in the group name)?

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/reduction.py
> +    )
This grouping is McStas specific, move into the load function (ScippNeXus returns grouped events already).

2023-12-13 07:34 UTC, SimonHeybrock commented on src/ess/nmx/detector.py
> +}
Is all this required? Can it not be detector from the input data? It seems the McStas loader is anyway using hard-coded 3 detectors.

2023-12-13 13:39 UTC, YooSunYoung commented
@Justin-Bergmann 

We have a couple of questions for you about this McStas loader...!

## Will you ever need non-grouped data?
If not, we will just always group them into pixel IDs when you load a file.

## Are p_x_y_n_id_t these variables always in the McStas simulation? 
We would like to know what's the minimum requirements of NMX McStas simulation data event list name.
For example, if the event data path in the h5 file ``entry1/data/bank01_events_dat_list_p_x_y_n_id_t`` must contain at least _p_ _id_ _t_ .

And we're going to hard-code the translation of each field, for example `p` is always `weights`.
So please let us know if the names might change in the McStas files...!

2023-12-13 15:49 UTC, Justin-Bergmann commented on src/ess/nmx/detector.py
> +}
in principle, we can have more or less  detector panels

2023-12-13 15:52 UTC, YooSunYoung commented on src/ess/nmx/loader.py
> +            raise NotImplementedError("Measurement data loader is not implemented yet.")
> This is not going to work. "ESS" NeXus files may also have an entry named "entry1" (naming is arbitrary). I think we should not attempt to auto-detect the file. Simply remove everything that is not for McStas. Name the function load_mcstas or something like that?

Yes, I removed that part. So users should just use different provider for loading depending on the file...? 

> Not sure it matters here, but you could also look for a unique top-level entry (this is the most common case), instead of a fixed name.

I don't what you mean by unique top-level entry...

2023-12-13 15:52 UTC, YooSunYoung commented on src/ess/nmx/detector.py
> +}
Yes... they should be included in the file as well... I was procrastinating parsing the detector information...

2023-12-13 15:53 UTC, Justin-Bergmann commented
> @Justin-Bergmann
> 
> We have a couple of questions for you about this McStas loader...!
> 
> ## Will you ever need non-grouped data?
> If not, we will just always group them into pixel IDs when you load a file.
> 
> ## Are p_x_y_n_id_t these variables always in the McStas simulation?
> We would like to know what's the minimum requirements of NMX McStas simulation data event list name. For example, if the event data path in the h5 file `entry1/data/bank01_events_dat_list_p_x_y_n_id_t` must contain at least _p_ _id_ _t_ .
> 
> And we're going to hard-code the translation of each field, for example `p` is always `weights`. So please let us know if the names might change in the McStas files...!

Spontaneously, I can not imagine any situation where we would use non-grouped data and we still have all information available. So please go ahead.

Yes, each simulation must contain p, id and t and as far as I know  all p_x_y_n_id_t are always in the simulation

The names will never change as long its not changed in the code itself

2023-12-14 07:25 UTC, SimonHeybrock commented on docs/examples/workflow.ipynb
> +    "``MaximumProabability`` can be manually provided to the loader derive more realistic number of events. <br>\n",
Spelling.

Also, since this is in the "nmx" package, can we drop the "nmx" from the function name? I'd suggest `load_mcstas_nexus`, for example (since we cannot load other McStas files, only NeXus).

2023-12-18 07:40 UTC, SimonHeybrock commented on src/ess/nmx/loader.py
> +            raise NotImplementedError("Measurement data loader is not implemented yet.")
> I don't know what you mean by unique top-level entry...

Ever NeXus file has one or more "entries" at the file root. Most files have just one, but the name is arbitrary.

2023-12-18 07:53 UTC, SimonHeybrock requested changes

2023-12-18 07:53 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    var = original_var.astype(dtype) if dtype else original_var
```suggestion
    var = original_var.astype(dtype, copy=False) if dtype else original_var
```

2023-12-18 07:53 UTC, SimonHeybrock commented on src/ess/nmx/__init__.py
> +    "DefaultMaximumProbability",
I think we should keep McStas-load specific params in the McStas module, and not import on the root level?

2023-12-18 07:53 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +        return NMXData(grouped.fold(dim='id', sizes={'panel': panels, 'id': -1}))
This looks broken since pixel-IDs are always for 3 panels? I would suggest to simply remove the panels option. I think we will simply get empty event lists in the case?

2023-12-18 07:53 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +            return key
You seem to be checking for keys in arbitrary order here? Below you are using hard-coded column indices. Before making such a generalization, consider carefully:

- Is it actually required?
- What can break if I generalize?
- Is it worth the effort (including writing unit tests for the generalization!)?

In this case I think the generalization should be removed, just check for the known fixed order.

2023-12-20 05:38 UTC, SimonHeybrock commented on src/ess/nmx/detector.py
> +    NumberOfDetectors: NumberOfDetectors(3),
Partially unused now?

2023-12-20 12:06 UTC, YooSunYoung commented on src/ess/nmx/detector.py
> +    NumberOfDetectors: NumberOfDetectors(3),
I think none of them are used actually... I'll just remove this module.

2023-12-20 13:23 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    var = original_var.astype(dtype, copy=False) if dtype else original_var
One final question. Can we use
```suggestion
    var = var['dim_1', idx].astype(dtype or var.dtype , copy=True)
```
to avoid up to one copy?

2023-12-21 08:21 UTC, SimonHeybrock commented on src/ess/nmx/mcstas_loader.py
> +    max_prop: Optional[MaximumProbability] = None,
```suggestion
    max_prob: Optional[MaximumProbability] = None,
```
or do not abbreviate?

2023-12-21 09:11 UTC, SimonHeybrock approved these changes

2023-12-21 09:11 UTC, merged